const fs = require('fs');
let content = fs.readFileSync('app.js', 'utf8');

const oldRegex = /const imgAreaHTML = card\.imageData\s*\? <img class="ic-premium-card-img" src="\$\{card\.imageData\}" alt="\$\{card\.label\}" loading="lazy">\s*<div class="ic-premium-value-badge"><i data-lucide="tag" style="width:14px; height:14px;"><\/i> \$\{card\.label \|\| 'Unnamed'\}<\/div>\s*: <div style="display:flex;align-items:center;justify-content:center;height:100%;color:var\(--text-muted\);"><i data-lucide="image-off" style="width:36px;height:36px;"><\/i><\/div>;\s*item\.innerHTML = \s*<div class="ic-premium-image-wrap">\$\{imgAreaHTML\}<\/div>\s*<div class="ic-premium-card-footer">\s*<div class="ic-premium-card-details">\s*<span class="ic-premium-card-title">\$\{displayLabel\}<\/span>\s*<span class="ic-premium-card-date">\$\{displayDate\}<\/span>\s*<\/div>\s*<div class="ic-premium-card-actions">\s*<button class="ic-premium-icon-btn ic-edit" title="Edit Card"><i data-lucide="edit-3"><\/i><\/button>\s*<button class="ic-premium-icon-btn ic-share" title="Share Options"><i data-lucide="share-2"><\/i><\/button>\s*<button class="ic-premium-icon-btn ic-delete" title="Delete Card"><i data-lucide="trash-2"><\/i><\/button>\s*<\/div>\s*<\/div>\s*;/g;

const newHtml = 'const badgeHTML = <div class="ic-premium-value-badge"><i data-lucide="tag" style="width:14px; height:14px;"></i> </div>;\\n\\n            const imgAreaHTML = card.imageData\\n                ? <img class="ic-premium-card-img" src="" alt="" loading="lazy">\\n                : <div style="display:flex;align-items:center;justify-content:center;height:100%;color:var(--text-muted);"><i data-lucide="image-off" style="width:36px;height:36px;"></i></div>;\\n\\n            item.innerHTML = \\n                <div class="ic-premium-image-wrap">\\n                    \\n                    <div class="desktop-badge-wrapper"></div>\\n                </div>\\n                \\n                <div class="mobile-only-title" style="display:none; text-align:center; font-size:1.5rem; font-weight:800; margin-bottom:8px;"></div>\\n                \\n                <div class="mobile-only-badge" style="display:none; text-align:center; margin-bottom:20px;">\\n                    <div class="ic-premium-value-badge" style="position:static; display:inline-flex;">\\n                        <i data-lucide="tag" style="width:14px; height:14px;"></i> \\n                    </div>\\n                </div>\\n\\n                <div class="ic-premium-card-footer">\\n                    <div class="ic-premium-card-details desktop-only-details">\\n                        <span class="ic-premium-card-title"></span>\\n                        <span class="ic-premium-card-date"></span>\\n                    </div>\\n                    \\n                    <div class="ic-premium-card-actions">\\n                        <button class="ic-premium-icon-btn ic-edit desktop-only-action" title="Edit Card"><i data-lucide="edit-3"></i></button>\\n                        <button class="ic-premium-icon-btn ic-share" title="Share Options"><i data-lucide="share-2"></i></button>\\n                        <button class="ic-premium-icon-btn ic-delete desktop-only-action" title="Delete Card"><i data-lucide="trash-2"></i></button>\\n                    </div>\\n                </div>\\n            ;';

content = content.replace(oldRegex, newHtml);
fs.writeFileSync('app.js', content);
console.log('App.js patched successfully!');
